### ISSUE TITLE
Using named routes with params seems not to work with $localeRote

### ISSUE THREAD

**Issue by exophunk** [s00d/nuxt-i18n-micro#10]
Reproduction: https://stackblitz.com/edit/nuxt-starter-zhtyjz?file=pages%2Findex.vue

Whenever I try to use a route with route parameters, it does not work when using with `$localeRoute()`. As far as tried, I could not use route parameters in any of those cases:
- Using default nuxt page naming convention with `[id]` for param
- Using localized route names or not
- Using `$localeRoute` with named routes like `{ name: 'page', params: { id: 'abc' }}`
- Using `$localeRoute` with paths like `/page/id-123`

It throws an error saying the param is not found, like:
`Missing required param "id"`

**Comment by AmrElabbasy** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by exophunk** [comment]
Fixed 99%. Thank you

The issue persists for
`<NuxtLink :to="$localeRoute('/page/id-123')"> Broken Link </NuxtLink>`

everything else is fine. thank you!

Updated reproduction with 1.13.4: https://stackblitz.com/edit/nuxt-starter-gax6db?file=pages%2Findex.vue

**Comment by s00d** [comment]
fixed 100% :)
