### ISSUE TITLE
[FEATURE] Replicate the folder structure of "pages" and do the same with "components"

### ISSUE THREAD

**Issue by agracia-foticos** [s00d/nuxt-i18n-micro#12]
Replicate the folder structure of "pages" and do the same with "components". Is it possible? Does it make sense?

**Comment by s00d** [comment]
Hi, integrating this feature would significantly complicate the module, introduce numerous unnecessary requests during page retrieval, and increase the overall load on the project. In my opinion, this approach lacks a clear purpose. From a technical perspective, this functionality can already be achieved using [definei18nroute](https://s00d.github.io/nuxt-i18n-micro/api/methods#%F0%9F%9A%A6-definei18nroute-routedefinition-locales-string-record-string-record-string-translationobject-localeroutes-record-string-string)

**Comment by agracia-foticos** [comment]
@s00d  perfect!! thanks!!
