### ISSUE TITLE
Plural is not a function in nuxt.config.ts

### ISSUE THREAD

**Issue by agracia-foticos** [s00d/nuxt-i18n-micro#14]
**Describe the bug**
[A clear and concise description of what the bug is.](error: VUE:ERROR : error.message:'plural is not a function',)

**To Reproduce**
Put  

```
i18n : {
  
     plural: (count:any, options:any) => {
        console.log('count', count)
        console.log('options', options)
        return count === 1 ? options.one : options.other;
    }
```
 }, in nuxt.config.ts

we want aply diferent plural in CS and PL

**Comment by s00d** [comment]
Hello.
Plural needs to be passed as a string, unfortunately, at the moment, I haven't come up with a better way. As soon as I think of something better, I'll redo it.

https://github.com/s00d/nuxt-i18n-micro/blob/a884b68755d547af9c7687655276e1407f7f4420/src/module.ts#L54

**Comment by s00d** [comment]
Fixed in version 1.15.4, now you can pass a function.
[docs](https://s00d.github.io/nuxt-i18n-micro/guide/getting-started#%F0%9F%94%A2-plural-function)

**Comment by agracia-foticos** [comment]
Y put 
`plural: (translation: unknown, count: number, locale: string) => {
        console.log('translation', translation)
        console.log('count', count)
        console.log('locale', locale)
        const forms = translation!.toString().split('|')
        if (count === 0 && forms.length > 2) {
          return forms[0].trim() // Case for "no apples"
        }
        if (count === 1 && forms.length > 1) {
          return forms[1].trim() // Case for "one apple"
        }
        return (forms.length > 2 ? forms[2].trim() : forms[forms.length - 1].trim()).replace('{count}', count.toString())
      }`

@s00d   But in noone place is printing console.log... Is aplying this code?? Works ok??

**Comment by agracia-foticos** [comment]
@s00d this plural function falls short

In 18next https://www.i18next.com/translation-function/plurals#languages-with-multiple-plurals plurals can be in diferent keys...

Maybe can modify plural function in this way

plural: (key:string, translation: string, count: number, locale: string, t:void) => {

key => the key, to search XXX_0, XXXX_1, etc... 
t, to avoid put another t('XXXXX_1')

**Comment by s00d** [comment]
I have reworked the logic of the plural function. Please check the [documentation](https://s00d.github.io/nuxt-i18n-micro/guide/getting-started#%F0%9F%94%A2-plural-key-string-translation-unknown-count-number-locale-string-string)

**Comment by s00d** [comment]
If you have any additional suggestions, errors, or comments, please open a new pull request.
