### ISSUE TITLE
HMR and Hydration errors in console

### ISSUE THREAD

**Issue by muhammedjenos** [s00d/nuxt-i18n-micro#18]
**Describe the bug**
While in development, updating the locale files doesnt trigger HMR. Manual refresh of the page updates the data indeed, but browser console is filled with hydration errors for the updated content elements

**Expected behavior**
Contents update during HMR without manual refresh and no console hydration errors

**Screenshots**
<img width="758" alt="image" src="https://github.com/user-attachments/assets/00c128ae-2888-46aa-9ab5-0026ac55e89f">

**Dev Setup**
 - MacOS Sequoia
 - Brave / Chrome

**Comment by s00d** [comment]
Hi, I’ve increased the file watching depth to 2 during development in version 1.19.1.
