### ISSUE TITLE
Add global localeRoutes configuration

### ISSUE THREAD

**Issue by tirojal** [s00d/nuxt-i18n-micro#22]
I working on nuxt3 project that consist of multiple modules. Each module adds it's own pages. I need a way to localize routes of those pages. I cannot use $defineI18nRoute since the project can be build for different countries with different locales. I evaluating it during build.
Also I need some pages to be on exact routes as they were added (no locale-route should be created) (especially if includeDefaultLocaleRoute === true)

So can we add new field to i18n-micro configuration?

I see structure of it like that:
``` ts
type GlobalLocaleRoutes = Record<string, Record<string, string> | false > | null | undefined
const globalLocaleRoutes: GlobalLocaleRoutes = { 'page-name': { localeCode: '/localeRoute' } }
```
example:
```js
// nuxt.config.ts
export default defineNuxtConfig({
  i18n: {
    // ...
    globalLocaleRoutes: { 
      // pages/page.vue
      'page': {
        en: '/page',
        de: '/seite',
        ru: '/stranitsa',
      },

      // pages/dir1/[slug].vue
      'dir1-slug': {
        en: '/dir-one/:slug()',
        de: '/dir-eins/:slug()',
        ru: '/dir-odin/:slug()',
      },

      // pages/dir2/[[slug]].vue
      'dir2-slug': {
        en: '/dir-two/:slug()?',
        de: '/dir-zwei/:slug()?',
        ru: '/dir-dva/:slug()?',
      },

      // pages/unlocalized.vue
      'unlocalized': false, // => will not create localaized route
    },
  }
}
```

**Comment by s00d** [comment]
hello. try v1.20.0 [docs](https://s00d.github.io/nuxt-i18n-micro/guide/getting-started#%F0%9F%8C%90-globallocaleroutes)

**Comment by tirojal** [comment]
Wow! That was fast :)
I'll try it tomorrow morning. 

Hope there will be bugs with includeDefaultLocaleRoute

**Comment by tirojal** [comment]
Seems like when includeDefaultLocaleRoute === true unlocalized route will never be reached because of middleware

**Comment by s00d** [comment]
Everything is logical: in the case of includeDefaultLocaleRoute, you need to set the locale in which you want to see the page, as this mode automatically enables a redirect to the default locale.

**Comment by tirojal** [comment]
I just finally ran the code.
As I expected middleware is doing redirection and unlocalized.vue is unreachable with that configuration:
```
{
    includeDefaultLocaleRoute: true,
    globalLocaleRoutes: {
      // pages/page.vue
      'page': {
        en: '/pageEN',
        de: '/seite',
        ru: '/stranitsa',
      },

      // pages/dir1/[slug].vue
      'dir1-slug': {
        en: '/dir-one/:slug()',
        de: '/dir-eins/:slug()',
        ru: '/dir-odin/:slug()',
      },

      // pages/unlocalized.vue
      'unlocalized': false,
    },
}
```

**Comment by tirojal** [comment]
https://github.com/s00d/nuxt-i18n-micro/issues/24
