### ISSUE TITLE
Question: Unused dependencies

### ISSUE THREAD

**Issue by tirojal** [s00d/nuxt-i18n-micro#26]
Why there is `ps-node@^0.1.6` as dependency
and why `pidusage@^3.0.2` as devDependency
\+ corresponding `@types/*` packages

I found no use them in the code

**Comment by s00d** [comment]
These are leftovers from the old performance.test.ts when I was running processes through these dependencies, but over time I stopped using them and forgot to delete them. I’ve cleaned it up now, thank you.

I have to make a lot of changes, and I might forget something. If you find anything else, please let me know.

**Comment by tirojal** [comment]
@s00d found one more:  `execa`

**Comment by s00d** [comment]
cleanup, thx
