### ISSUE TITLE
Prerender error - Page not found

### ISSUE THREAD

**Issue by kleinpetr** [s00d/nuxt-i18n-micro#29]
**Describe the bug**
During the prerender process I am facing a bug about 
```
Error: [404] Page not found: /en/api/_content/cache.1728374969913.json
```

**To Reproduce**
1. Install Nuxt Content
2. Install i18n micro
3. define 2 languages
4. disable pageLocales
5. create 2 pages (index.vue, about.vue)
6. run `pnpm generate` or `pnpm build`

**Expected behavior**
Prerender pages

**Screenshots**
![image](https://github.com/user-attachments/assets/8c80dd25-3318-46b2-981f-e1d7a91027d8)

**Desktop (please complete the following information):**
 - OS: Linux Fedora Workstation 40
 - Browser LibreWolf 130.0
 - Version 1.21.5

**Reproduction**
https://stackblitz.com/github/kleinpetr/nuxt-content-i18n_micro?file=README.md

**Comment by s00d** [comment]
Hello. Great, thank you very much for the example. I found the issue and fixed it. Try version v1.22.0.

**Comment by kleinpetr** [comment]
Awesome, thanks :pray:
