### ISSUE TITLE
Layer specefic locales Support

### ISSUE THREAD

**Issue by OsamaHaikal** [s00d/nuxt-i18n-micro#3]
How to use the current module with Nuxt layers if each layer has a locales DIR? It would be great if the module could support defining locales for specific layers  within a project. This would help keep things organized, especially in larger apps.

**Comment by s00d** [comment]
Hi @OsamaHaikal,

Thank you for your suggestion! I'm happy to inform you that support for working with layers has been added in the latest release of `Nuxt I18n Micro`. With this new feature, you can now define and manage locales specifically for different layers within your project. This enhancement is particularly useful for larger applications, where organizing translations by layer can significantly improve maintainability and clarity.

You can find the details of this new feature in the release notes here:
[Release v1.3.0](https://github.com/s00d/nuxt-i18n-micro/releases/tag/v1.3.0)

Additionally, you can review the specific commit where this feature was implemented:
[Commit 6e099e16e2a2ce7ec17daee1c01ccdc670e2ecf6](https://github.com/s00d/nuxt-i18n-micro/commit/6e099e16e2a2ce7ec17daee1c01ccdc670e2ecf6)

For more detailed instructions and examples on how to utilize layers within your project, please refer to the updated documentation:
[Documentation - Layers](https://github.com/s00d/nuxt-i18n-micro?tab=readme-ov-file#layers)

I hope this new functionality meets your needs, and please feel free to reach out if you have any further questions or feedback!
