### ISSUE TITLE
Add feature to reuse localisation files

### ISSUE THREAD

**Issue by Rigo-m** [s00d/nuxt-i18n-micro#36]
Let's say we have iso code routes (i.e.: locale codes are en-us, en-gb, de-de, de-at); the module will then create 4 global localisation files, but we actually have 2 locales.

Adding a `file` config would be helpful to maintain only 2 localisations json for these 4 locales.

e.g.:
```ts
locales: [
  { code: 'en-us', iso: 'en-US', dir: 'ltr', file: 'en.json' },
  { code: 'en-gb', iso: 'en-GB', dir: 'ltr', file: 'en.json' },
  { code: 'de-de', iso: 'de-DE', dir: 'ltr', file: 'de.json' },
  { code: 'de-AT', iso: 'de-at', dir: 'ltr', file: 'de.json' },
]
```

**Comment by s00d** [comment]
It seems to me that such functionality introduces unnecessary complexity. From a practical perspective, this approach doesn’t offer any performance gains or improve the logic. Instead, it introduces a lot of redundant conditions, which only leads to more issues and potential bugs.

As the saying goes, "Penny wise, pound foolish."

**Comment by Rigo-m** [comment]
I could fix this quickly with a module that "paste" localisation files in relevant global translations file.
Closing as not planned then.
I understand your point of view, my request is coming from someone who's trying to migrate in the quickest way possible from nuxt-i18n :) Thanks for your amazing work
