### ISSUE TITLE
Pluralization like vue i18n with pipes

### ISSUE THREAD

**Issue by Met96** [s00d/nuxt-i18n-micro#40]
Hi, it would be great the pluralization handle wil be like Vue I18n with pipe (|) separator.
Because now i tried it in a personal project but i have many problems.

Like "productsCart": "1 product | {n} products"

Example:
$tc('productsCart', 1) --> 1 product
$tc('productsCart', 4) --> 4 products

link doc: https://kazupon.github.io/vue-i18n/guide/pluralization.html

**Comment by s00d** [comment]
Currently, everything is set up with |.

You can modify the method's logic in plural; the documentation explains everything. Here's an example: https://github.com/s00d/nuxt-i18n-micro/blob/bcaacc35eee77403b3c73d20cb4e69b1c03e0fb8/playground/nuxt.config.ts#L63 https://github.com/s00d/nuxt-i18n-micro/blob/bcaacc35eee77403b3c73d20cb4e69b1c03e0fb8/playground/locales/pages/page/en.json#L3 https://github.com/s00d/nuxt-i18n-micro/blob/bcaacc35eee77403b3c73d20cb4e69b1c03e0fb8/playground/pages/page.vue#L29

**Comment by Met96** [comment]
Amazing! Thanks for the example!
