### ISSUE TITLE
Type conficts between $t and useSeoMeta()

### ISSUE THREAD

**Issue by polarove** [s00d/nuxt-i18n-micro#43]
**Is your feature request related to a problem? Please describe it.**

In nuxt

```typescript
useSeoMeta({
    // error: Type 'unknown' is not assignable to type 'Title | undefined'
    title: t('title')
})
```

I am ok with type cast, but this is kind of unacceptable
Am I missing something from the documentation?
```typescript
useSeoMeta({
    title: t('title', { name: t('name') as string }) as string,
    description: t('description') as string,
    ogTitle: t('ogTitle') as string,
    ogDescription: t('ogDescription') as string,
    ogImage: 'http://example.com/example.png',
    ogUrl: 'http://example.com/',
    twitterTitle: t('twitterTitle') as string,
    twitterDescription: t('twitterDescription') as string,
    twitterImage: 'http://example.com/example.png',
    twitterCard: 'app'
})
```

**Describe the solution you'd like**
[suggested] add a new function that wraps `useSeoMeta` with intl abilities

**Describe alternatives you've considered**
[breaking change] rewrite and then mark the return type of `t()` or `$t()` as `string | undefined`, or something like that.
(I know this is terrible)

**Additional context**
None

**Comment by s00d** [comment]
I can simply add a TypeScript function (ts) that returns a string.

**Comment by s00d** [comment]
Added $ts
