### ISSUE TITLE
Typecheck issue from i18n-switcher compoent

### ISSUE THREAD

**Issue by Met96** [s00d/nuxt-i18n-micro#47]
Hi have this error by typecheck. I think is only an "auto" word not set to Locale interface inside the file
<img width="1285" alt="Screenshot 2024-10-17 alle 17 39 49" src="https://github.com/user-attachments/assets/e3944edf-e64c-4651-8d20-0c9293f212c4">

**Comment by s00d** [comment]
https://github.com/s00d/nuxt-i18n-micro/releases/tag/v1.26.1

fixed
