### ISSUE TITLE
What's the purpose of warning: Bad format?

### ISSUE THREAD

**Issue by polarove** [s00d/nuxt-i18n-micro#48]
**Describe the bug**
https://github.com/s00d/nuxt-i18n-micro/blob/9d77151cb6a77a277674ede0fd776adb71799f8d/src/runtime/plugins/01.plugin.ts#L307
https://github.com/s00d/nuxt-i18n-micro/blob/9d77151cb6a77a277674ede0fd776adb71799f8d/src/runtime/plugins/01.plugin.ts#L308

**Comment by s00d** [comment]
it's bag :) fixed
