### ISSUE TITLE
NuxtLink resets current locale

### ISSUE THREAD

**Issue by kleinpetr** [s00d/nuxt-i18n-micro#49]
Hello,

it seems that the package can't handle links via `<NuxtLink>` since it always resets the URL prefix.. I guess that standard i18n could do it, at least with `no_prefix` strategy.

Is there any possibility to use this strategy here? 

On the other hand it would be nice to add a composable like `navigateToI18n()` which could replace native `navigateTo()` util

**Comment by s00d** [comment]
https://github.com/s00d/nuxt-i18n-micro/blob/85ddc391abccecd3a32ae1059de34050dc40babc/playground/pages/page.vue#L67

**Comment by s00d** [comment]
try [switchRoute](https://s00d.github.io/nuxt-i18n-micro/api/methods#%F0%9F%94%84-switchroute) in v1.27.0
