### ISSUE TITLE
docs: mistake 

### ISSUE THREAD

**Issue by reslear** [s00d/nuxt-i18n-micro#5]
кажется тут нет разницы в примерах может быть стоит удалить этот пункт либо имеется ввиду удалить импорты и использовать глобальный?

![CleanShot 2024-08-21 at 18 49 27@2x](https://github.com/user-attachments/assets/83109f21-de15-4aaa-8516-6a742e2304ba)

**Comment by s00d** [comment]
fixed https://github.com/s00d/nuxt-i18n-micro/commit/f2840bd78a07048059f6840e5fe97320c82979f7
