### ISSUE TITLE
Setting the base path via env variable (NUXT_APP_BASE_URL) 

### ISSUE THREAD

**Issue by MariaAndreyeva** [s00d/nuxt-i18n-micro#52]
**Issue Summary:**

Nuxt 3 supports setting the base path via the configuration file or environment variables. However, the nuxt-i18n-micro library does not seem to support setting the base URL through the environment variable NUXT_APP_BASE_URL.

**Steps to Reproduce:**

Set the base URL in the nuxt.config.js file:
```
export default defineNuxtConfig({
  app: {
    baseURL: '/prefix/'
  }
})
```
Build the application:
`npm run build`
Change the base path using the environment variable and run the server:
`NUXT_APP_BASE_URL=/test/ node .output/server/index.mjs`
Access the application at localhost:3000/test/.
Expected Behavior:
The application should be served with the new base path /test/ and should work as expected.
Actual Behavior:
The application does not work as expected, and the following warning is displayed in the console:
[Vue Router warn]: No match found for location with path "/prefix/_locales/general/en/data.json"

**Environment:**

Nuxt Version: 3.13.2
nuxt-micro-i18n Version: 1.22.1
Node Version: 20.10.0
Operating System: MacOS 

**Additional Information:**

The issue seems to be related to the nuxt-i18n-micro library not respecting the NUXT_APP_BASE_URL environment variable.
The application works correctly when the base path is set directly in the nuxt.config.js file.

**Possible Cause:**

The nuxt-micro-i18n library might be using the base URL defined in the nuxt.config.js file and not overriding it with the environment variable NUXT_APP_BASE_URL.

**References:**
[Nuxt Configuration Documentation](https://nuxt.com/docs/api/nuxt-config#baseurl)

Thank you for your attention to this matter.

**Comment by s00d** [comment]
tried locally
NUXT_APP_BASE_URL=/test/ npm run build
NUXT_APP_BASE_URL=/test/ node .output/server/index.mjs

everything works as expected, requests went to http://localhost:3000/test/_locales/, it seems the issue is somewhere else. There's also the [apiBaseUrl](https://s00d.github.io/nuxt-i18n-micro/guide/getting-started#%F0%9F%94%97-apibaseurl) parameter, and it might conflict with NUXT_APP_BASE_URL. Have you changed it? Try configuring it; maybe this will help.

<img width="709" alt="image" src="https://github.com/user-attachments/assets/7fef8eff-5b02-4e63-9719-f21c09c63b49">

**Comment by s00d** [comment]
I tried to simultaneously pass a parameter through env and config, resulting in some kind of strange conflict. Nuxt starts with the prefix from the config, and I'm not sure if it's possible to do it this way. If I use only the config or only env, everything works as it should

**Comment by MariaAndreyeva** [comment]
Thank you for checking. Can you try to build without setting NUXT_APP_BASE_URL=/test/ during build? In our case we build app once, but serve multiple times with different env variables to change the prefix for every website.

**Comment by s00d** [comment]
fixed, try v1.27.1

**Comment by MariaAndreyeva** [comment]
Thank you so much for your help! It's truly the best support I have ever experienced. And your library is pretty cool! We recently transitioned from Nuxt i18n, and I am impressed. It has everything we need: localized routes, SEO and dynamic loading of translations.

You're doing a great job!

**Comment by s00d** [comment]
thank you for your feedback

**Comment by s00d** [comment]
[here](https://github.com/s00d/nuxt-i18n-micro/issues/44)
