### ISSUE TITLE
Typecheck - multiple type errors

### ISSUE THREAD

**Issue by DomWane** [s00d/nuxt-i18n-micro#53]
"nuxt-i18n-micro": "^1.29.0",

'__VLS_ctx.$localeRoute' is of type 'unknown'.
 '$localeRoute' is of type 'unknown'.
'$getLocales' is of type 'unknown'.
'$getLocale' is of type 'unknown'.
'$getLocaleName' is of type 'unknown'.
'$localeRoute' is of type 'unknown'.

<img width="744" alt="err" src="https://github.com/user-attachments/assets/e7c90d55-cf28-4f1c-88b5-d35e6e295baf">

**Comment by s00d** [comment]
hello. try [composables](https://s00d.github.io/nuxt-i18n-micro/composables/useI18n)

I removed all the typing, it works terribly and breaks every other time. For composables, everything should work.
