### ISSUE TITLE
Does not work with SSG (Static Site Generation)

### ISSUE THREAD

**Issue by ammo8600** [s00d/nuxt-i18n-micro#59]
**Describe the bug**
The module does not work with SSG, Just some blank pages are generated. 

However, it is generating the pages, folders for each language, but not the HTML content. I have searched the docs and issues, found nothing. Can this module handle this feature, or should I use any other solution.

**Comment by s00d** [comment]
The module definitely works in SSG; this is essentially its main function. I'm testing it on three projects, and you can test it in the project playground to find out what the problem is. I need an example.

**Comment by ammo8600** [comment]
Okay.  I'll check and comment on what I find. Assuming some config issue.

**Comment by ammo8600** [comment]
Okay, here is what I have found. 

Using the autoDetectPath: '/' is the only way, but generates only the non-default locales with the content.

No content is generated for the default locale's index.html. This is what's inside.

<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=/"></head></html>

**Comment by s00d** [comment]
Please make a simple example where I can see the problem. It’s not clear otherwise.

**Comment by ammo8600** [comment]
Okay, i have set up a repo for this. 

https://github.com/ammo8600/test-nuxt-i18n-micro

Can you take a look.

**Comment by s00d** [comment]
> Okay, i have set up a repo for this.
> 
> https://github.com/ammo8600/test-nuxt-i18n-micro
> 
> Can you take a look.

I checked your example, and everything works great. Maybe the issue is with the OS? What OS are you using? How are you running it? Describe in more detail, as I don't see any problems so far.

**Comment by s00d** [comment]
> Running POP OS (Linux), Node v22.11.0
> 
> Can you take a look at the default index.html in the generated ./output/public folder. You'll see what I mean.
> 
> ![image](https://private-user-images.githubusercontent.com/25807287/383211146-0db7d7f8-bdb2-46b6-9124-5298096281bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4Mjc5NDUsIm5iZiI6MTczMDgyNzY0NSwicGF0aCI6Ii8yNTgwNzI4Ny8zODMyMTExNDYtMGRiN2Q3ZjgtYmRiMi00NmI2LTkxMjQtNTI5ODA5NjI4MWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDE3MjcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmZDVjM2JmMzU1Y2VjNmVkOThlOTZlY2M0MzNmOTdhOTBiYzI1Zjc5YmM2MjI2ZmViMDQ2YTYxZmI3NGQ0YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bLFEJ9PaCMxW6JSkcUVS6w48dZ0y7vsuIZGCGcptesg)

That's correct. This happens because you have the includeDefaultLocaleRoute mode enabled. In this case, the content is generated in locale-specific folders, such as .output/public/de/index.html, and the default route is used only for redirection.

**Comment by ammo8600** [comment]
Okay, got it working. Had to use the following config.

`i18n: {
    debug: true,
    locales: [
      {code: 'en', iso: 'en', disabled: false},
      {code: 'fr', iso: 'fr', disabled: false},
      {code: 'de', iso: 'de', disabled: false},
    ],
    meta: true,
    defaultLocale: 'en',    
    translationDir: 'locales',
    autoDetectLanguage: false,
    autoDetectPath: '/',
    metaBaseUrl: 'https://example.com',
    includeDefaultLocaleRoute: false,
  },`
  
  making the autoDetectLanguage and includeDefaultLocaleRoute to false.

**Comment by s00d** [comment]
I figured out what the issue was: in SSG mode, an auto-redirect was triggered. I fixed it in version v1.31.7.
