### ISSUE TITLE
Nuxt website with i18n-micro refresing again and again into an infinite loop on Cloudflare pages

### ISSUE THREAD

**Issue by Met96** [s00d/nuxt-i18n-micro#60]
**Describe the bug**
We tried to create a project with i18n-micro but we had some problems of infinite refresh.

**To Reproduce**
1. Create repo with latest nuxt version
2. Install nuxt-hub/core and i18n-micro
3. Create an index.vue page with an example of translation
4. Add NITRO_PRESET=cloudflare-pages to nuxt build on package json
5. Follow the installation fo cloudflare https://hub.nuxt.com/docs/getting-started/deploy#self-hosted

**Comment by s00d** [comment]
Hello. Try v1.31.6, I fixed one bug and also added an error. For Cloudflare Pages, the module only works if `includeDefaultLocaleRoute` is set to `true`.

You can see an example here: https://test-hub-cloudflare-i18n.nuxt.dev/de

https://github.com/s00d/-Cloudflare-Pages-project
