### ISSUE TITLE
Multi Domain Locales - hreflang across domains

### ISSUE THREAD

**Issue by ammo8600** [s00d/nuxt-i18n-micro#62]
**Is your feature request related to a problem? Please describe.**
The module is missing one feature. Using the provided documentation for Multi Domain Locale and using Layers with SSG. 

A problem arises when we want to use "metaBaseUrl" It is fine for the current child layer as it generates hreflang tags for the current domain specified in the metaBaseUrl (Child Layer). Then if we have a second child-layer it will only generate URLs for its own metaBaseUrl.

But In a real-world SEO scenario, you want these tags to link between sites/domains. e.g

example.com/page [en-US]  > should link to > fr.example.com/page [fr-FR] 

likewise the other way around.

**Describe the solution you'd like**
I think we can leverage the locales array in the config from the base layer to have a URL property that defines the exact URL for the locale's location where it is served. And use that information to generate the link tags. If the URL is not defined for a specific locale then use the metaBaseUrl defined in the child-layer

**Comment by s00d** [comment]
Hello. I added this functionality, but I would strongly advise against this approach. In the documentation [here](https://s00d.github.io/nuxt-i18n-micro/guide/getting-started#%F0%9F%8C%8D-locales), I explained why.
