### ISSUE TITLE
No access of i18n instance in nuxt plugins

### ISSUE THREAD

**Issue by fabkho** [s00d/nuxt-i18n-micro#63]
Hi hi, i am currently in the process of migrating a huge application to your very promising package and encountered a major issue.

**Describe the bug**
The provided API ($t, $getLocale, $localePath etc.) cannot be used within Nuxt plugins, resulting in a runtime error.

**To Reproduce**
Try to use any nuxt-i18n-micro composable within the plugin:
```typescript
export default defineNuxtPlugin((nuxtApp) => {
  const { $getLocale } = nuxtApp.$i18n
  const locale = $getLocale() // error here
})
```
Error in console:
```
[nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at https://nuxt.com/docs/guide/concepts/auto-imports#vue-and-nuxt-composables
```

**Expected behavior**
The nuxt-i18n-micro composables should be accessible within Nuxt plugins, as plugins are a valid context for accessing Nuxt instance functionality. This would allow proper initialization and setup of i18n functionality at the plugin level.

**Environment Information**
- Nuxt Version: 3.13.2
- nuxt-i18n-micro version: latest
- Node Version: 20.11.0
- Package Manager: yarn
- Operating System: MacOS

**Comment by s00d** [comment]
Hello. 
You are not using i18n correctly; it should be done like this:

```typescript
export default defineNuxtPlugin((_nuxtApp) => {
  const { $t } = useI18n() // or const { $t } = useNuxtApp()
  const translatedMessage = $t('test_key')

  console.log(translatedMessage)
})
```

Also, while testing, I found a bug; please use version v1.32.2.

**Comment by s00d** [comment]
Now I understand the problem; just don’t use the function call like this:
```javascript
const val = nuxtApp.$t('common.errors.unknown.title')
showError({
    title: val
})
```
Instead, you need to use `runWithContext`, for example:
```javascript
await nuxtApp.runWithContext(() => $t('test_key'))
```

I’ll fix this issue later.

**Comment by s00d** [comment]
I slightly changed the logic in v1.32.4. Now this issue should occur less frequently, but it still can't be completely eliminated. More details are described here: https://nuxt.com/docs/api/composables/use-nuxt-app#runwithcontext.

**Comment by fabkho** [comment]
Man, the whole composable situation in the nuxt ecosytem is such a mess 😶‍🌫️

**Comment by s00d** [comment]
> Also one important detail for the docs may be that calling $t after an async request can break.

[added](https://s00d.github.io/nuxt-i18n-micro/guide/faq#%E2%9D%93-why-does-t-or-other-i18n-composables-not-work-in-nuxt-plugins)

> Man, the whole composable situation in the nuxt ecosytem is such a mess 😶‍🌫️

Yes, it's a relevant issue, but over time you get used to it and stop encountering it.

**Comment by alexcroox** [comment]
@fabkho you can also try to set this in your nuxt config which does eliminate some of those footguns:

```
experimental: {
    asyncContext: true
}
```

**Comment by s00d** [comment]
> Okay so i tried again to get this running, without success. The newest Version seems to have broken context in nuxt plugins completely now. Not even this works now:
> 
> export default defineNuxtPlugin((_nuxtApp) => {
>   const { $t, $getLocale } = useI18n() // or const { $t, $getLocale } = useNuxtApp()
>   const translatedMessage = $t('test_key')
>   const locale = $getLocale() // error here
> 
>   console.log(translatedMessage, locale)
> })
> If i switch back to v1.32.3 it works. The `asyncContext: true` does not do anything.

The issue is related to the plugin loading order. Previously, it was the first in the queue, but this caused hooks to not work. Now, I have moved it after the user plugins, which resolved the problem. However, now it's necessary to add `dependsOn` to the plugins that work with `i18n`, for example:

```javascript
export default defineNuxtPlugin({
  name: 'i18n:plugin',
  dependsOn: ['i18n-plugin-loader'],
  enforce: 'post',
  setup(_nuxtApp) {
    const { $t, $getLocale } = useI18n() // or const { $t, $getLocale } = useNuxtApp()
    const translatedMessage = $t('test_key')
    const locale = $getLocale() // error here

    console.log(translatedMessage, locale)
  },
})
```

**Comment by s00d** [comment]
Try version v1.71.0; I’ve reworked the logic, the old method should work now.
