### ISSUE TITLE
 i18n:register Hook Not Triggered on Initial Load

### ISSUE THREAD

**Issue by MariaAndreyeva** [s00d/nuxt-i18n-micro#69]
**Describe the bug**
I'm encountering an issue with the nuxt-i18n-micro library when loading translations dynamically(https://s00d.github.io/nuxt-i18n-micro/api/events#%F0%9F%9B%A0%EF%B8%8F-modifying-translations-with-plugins). The i18n:register hook is not being triggered during the initial load of the application, but it works correctly on subsequent route changes.

**To Reproduce**
1. Set up a Nuxt 3 application with nuxt-i18n-micro.
2. Register an [extend locales plugin](https://s00d.github.io/nuxt-i18n-micro/api/events#%F0%9F%9B%A0%EF%B8%8F-modifying-translations-with-plugins) to use the i18n:register hook to dynamically load translations.
3.Load the application in a browser.

**Expected behavior**
The i18n:register hook should be triggered on the initial load of the application to load the necessary translations.

**Actual Behavior:**
The i18n:register hook is only triggered during route changes, not during the initial load.

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: chrome
 - Version 1.32.4

**Additional context**
The issue appeared after upgrading nuxt-i18n-micro from version ^1.31.2 to ^1.32.4.

**Comment by s00d** [comment]
fixed, try v1.34.1

example
https://github.com/s00d/nuxt-i18n-micro/blob/57d0a2b72d9dc6213f8cf06f29c348ab80419244/playground/plugins/03.myPlugin.ts#L10
https://github.com/s00d/nuxt-i18n-micro/blob/57d0a2b72d9dc6213f8cf06f29c348ab80419244/playground/pages/index.vue#L4
