### ISSUE TITLE
Problems with MonoRepo and dynamic deployments

### ISSUE THREAD

**Issue by agracia-foticos** [s00d/nuxt-i18n-micro#7]
We are currently working with a monorepo project.

We are using i18n micro within one of our apps, not globally, but locally in the project.

The first problem that arises is that the rootDirs variable is including packages that do not have i18n

runtime.mjs
![image](https://github.com/user-attachments/assets/57b6b158-39dc-40dc-ad5e-230b0aefc427)

The second and more important problem is that this path is being burned into the compilation. The problem is that we move the project in the deployment, so this path does not exist for the translation files, since the project has been moved.
These paths should not be absolute, but relative or somehow be able to determine the rootDir

**Comment by s00d** [comment]
Hello, relative paths are not needed. During the refactoring, I forgot to move the logic for caching responses to locale requests. I've fixed it, please check it now(v1.12.5). I've also added a filter when forming the list of subfolders.

Everything in my setup is done very simply. During the production build, Nuxt generates the final JSON, so all these rootDirs are no longer used. The translations are served directly from the generated response.

**Comment by agracia-foticos** [comment]
@s00d Works!!! Thanks!!! :+1:

**Comment by s00d** [comment]
I also made rootDirs private for security reasons(1.13.1).
