### ISSUE TITLE
Upgrade https://s00d.github.io/nuxt-i18n-micro/guide/getting-started#%F0%9F%94%A2-plural documentation

### ISSUE THREAD

**Issue by agracia-foticos** [s00d/nuxt-i18n-micro#72]
Upgrade https://s00d.github.io/nuxt-i18n-micro/guide/getting-started#%F0%9F%94%A2-plural documentation

I think in last version this section have been updated

**Comment by s00d** [comment]
fixed

**Comment by agracia-foticos** [comment]
@s00d 

On new version 1.33.0 fails plural function
`error {
  url: '/',
  statusCode: 500,
  statusMessage: '',
  message: 't is not a function',
  stack: '<pre><span class="stack">at Module.plural (./.nuxt/i18n.plural.mjs:2:27)</span>\n' +
    '<span class="stack internal">at tc (/home/web/var/www/wpx/node_modules/nuxt-i18n-micro/dist/runtime/plugins/01.plugin.js:295:36)</span>\n' +
    '<span class="stack">at Module.getTranslationFromGroupCriteria (./src/utils/product.ts:100:28)</span>\n' +
    '<span class="stack">at setup (./src/components/Page/ProductThumb.vue:71:67)</span>\n' +
    '<span class="stack">at _sfc_main.setup (./src/components/Page/ProductThumb.vue:280:23)</span>\n' +
    '<span class="stack internal">at callWithErrorHandling (/home/web/var/www/wpx/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:200:19)</span>\n' +
    '<span class="stack internal">at setupStatefulComponent (/home/web/var/www/wpx/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7848:25)</span>\n' +
    '<span class="stack internal">at setupComponent (/home/web/var/www/wpx/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7809:36)</span>\n' +
    '<span class="stack internal">at renderComponentVNode (/home/web/var/www/wpx/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:645:15)</span>\n' +
    '<span class="stack internal">at Module.ssrRenderComponent (/home/web/var/www/wpx/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:86:10)</span></pre>'
}`

the function:
`plural: (key: string, count: number, _locale: string, t: Getter) => {
        const translation = t(key)
        if (!translation) {
            return key
        }   

        //0 items | 1 item | n items
        if (translation.includes('|')){
            const forms = translation.toString().split('|')
            if (count === 0 && forms.length > 2) {
                return forms[0].trim() // Case for "no apples"
            }
            if (count === 1 && forms.length > 1) {
                return forms[1].trim() // Case for "one apple"
            }
            return (forms.length > 2 ? forms[2].trim() : forms[forms.length - 1].trim()).replace('{count}', count.toString())
        }else{
            if (["pl", "cs"].includes(_locale)){
                if (count === 1) 
                    return t(`${key}_0`)
                else if (count>=2 && count<5)
                    return t(`${key}_1`)
                else
                    return t(`${key}_2`)
            }else{
                if (count === 1) 
                    return t(key)
                else
                    return t(`${key}_plural`)
            }
        }
    }`

**Comment by s00d** [comment]
Sorry, I fixed it in the wrong place. I’ve updated the documents again.

[Example](https://github.com/s00d/nuxt-i18n-micro/blob/4b73fc49e15ac1655257c30fa657edb485aefaa3/playground/nuxt.config.ts#L65)
