### ISSUE TITLE
Translations File Updates Before Async Functions Resolve

### ISSUE THREAD

**Issue by JulBeg** [s00d/nuxt-i18n-micro#75]
When navigating to a new page the translations file is updated before the resolution of async functions (e.g. useFetch)

**To Reproduce**
https://stackblitz.com/edit/nuxt-i18n-micro-async-bug

**Expected behavior**
The page's translations file should load after the asynchronous functions have fully resolved

**Comment by s00d** [comment]
Unfortunately, this behavior cannot be changed. The logic is designed to load the locale first, and I couldn't find an alternative solution. This approach has both its benefits and drawbacks.

If this is an issue for you, consider adding a loader to improve the user experience.

**Comment by JulBeg** [comment]
Finally I just disabled the pages locales (`disablePageLocales: true`) and it is working as expected with only the global translations files
