### ISSUE TITLE
Bug: Default Nested Route (index.vue) Not Loading

### ISSUE THREAD

**Issue by JulBeg** [s00d/nuxt-i18n-micro#78]
When using nested routes with a default child (index.vue), the child component fails to load.
This issue is caused by an extra `/.` appended to the child route's path.

![image](https://github.com/user-attachments/assets/ee3fc421-085c-4027-913c-8af8912fbd55)

**To Reproduce**
https://stackblitz.com/edit/nuxt-starter-4vjb8d
Remove the module from nuxt.config to see the difference

**Expected behavior**
![image](https://github.com/user-attachments/assets/3cc6d7d1-ea14-43dc-bb50-6984603788c7)

**Comment by s00d** [comment]
hello

https://s00d.github.io/nuxt-i18n-micro/guide/faq#%E2%9D%93-what-if-a-route-doesn-t-load

**Comment by JulBeg** [comment]
Same problem even after adding a route name to the children (index.vue), did you check the stackblitz ?
The problem is that the default child path is renamed (`/.` is appended) :

```javascript
-| profiles/
---| [id]/
-----| index.vue // This one is not loaded by default on route /profiles/[id]
---| [id].vue
```

**Comment by s00d** [comment]
I checked it, and it's a different error. Can you explain why you need this at all? I don’t understand why anyone would do this or how it could be useful. It looks more like a bug than something intentional.

**Comment by s00d** [comment]
fixed. try v1.38.1
