### ISSUE TITLE
[Feature]: Auto-detect on SSR

### ISSUE THREAD

**Issue by ChrisGV04** [s00d/nuxt-i18n-micro#8]
If I understand correctly, it seems like the current behavior for auto-detect only runs on the client-side, but not on the server for SSR.

Reading how `nuxt-i18n` works, it also allows auto-detection at the server by checking the `accept-language` HTTP header and only if that and `navigator.language` are not present it will fallback to the default locale.

What do you think about this feature?

Amazing work BTW!
This package looks very promising and I will definitely consider it for future production projects.

**Comment by s00d** [comment]
Yes, you are right, there was such an issue. I created a server-side plugin for redirects (1.12.6) and also added a new parameter, [autoDetectPath](https://s00d.github.io/nuxt-i18n-micro/guide/getting-started#%F0%9F%94%8D-autodetectpath-string), so you can enable redirects, for example, only on the home page.
