### ISSUE TITLE
Disable locale based URL routing

### ISSUE THREAD

**Issue by alexcroox** [s00d/nuxt-i18n-micro#80]
**Is your feature request related to a problem? Please describe.**
I'm coming from nuxt-i18n where I don't have anything related to i18n in the URL. 

In nuxt-i18n it:

1. On page load auto detects the user's locale
2. Auto switches to that locale if possible (doesn't change the page URL)
3. Saves a cookie with locale

Currently with nuxt-i18n-micro after deploying to production I was surprised to see the URL change:

from `example.com` to `example.com/en-GB`

How do I stop this redirect from happening? I would like the URL to remain as example.com no matter the chosen locale.

```
i18n: {
    locales: [
      {
        code: 'en-GB',
        iso: 'en-GB',
      },
      {
        name: 'French',
        code: 'fr-FR',
      },
      {
        name: 'German',
        code: 'de-DE',
      },
    ],
    includeDefaultLocaleRoute: false,
    defaultLocale: 'en-GB',
    fallbackLocale: 'en-GB',
    localeCookie: 'locale',
    disablePageLocales: true,
    autoDetectLanguage: false,
    meta: true,
  },
```

If change `includeDefaultLocaleRoute: false` I get the error:

` ERROR  Nuxt-i18n-micro: "includeDefaultLocaleRoute" must be set to true when using Cloudflare Pages.`

Thanks!

**Comment by alexcroox** [comment]
I've had some luck manually patching node_modules to return early when attempting to generate and prerender these localised routes:

![SCR-20241212-uamm](https://github.com/user-attachments/assets/76e46670-4b62-484c-ad6a-b2a391eb5f75)

![SCR-20241212-uatf](https://github.com/user-attachments/assets/715a7774-a0f1-4d9a-85b4-5f614ae2658a)

Is this something you'd consider as a configurable option?

**Comment by alexcroox** [comment]
@s00d do you think disabling locale based routes is in the scope of this project?

**Comment by s00d** [comment]
Hi,  

I’ve answered similar questions before. Disabling localized routes doesn’t really make sense because the whole point of this setup is to improve SEO. Without localized routes:  

1. Search engines won’t index your content correctly for different languages.  
2. You might face performance issues with SSR.  

If you don’t need localized routes, you probably don’t need these modules at all. [Vue I18n](https://vue-i18n.intlify.dev/guide/integrations/nuxt3.html) can do what you need out of the box with a simple plugin and a language switcher component.  

Can you explain your use case? Maybe there’s another way to solve your problem without breaking how the module is designed to work.

**Comment by alexcroox** [comment]
My apps are mostly behind authentication flows so SEO isn’t important, sometimes I won’t know ahead of time what locale the user has when sending emails or sms and sending links without locales, or the wrong locale, will cause an immediate redirect which can break some flows like Auth/OAuth. 

The apps are also multi tenant with custom domain support so likely the locale differences will be on the top level domain level eg .com, .fr etc

Google does also support the language header when crawling https://developers.google.com/search/blog/2015/01/crawling-and-indexing-of-locale

**Comment by s00d** [comment]
You've exhausted me with the no_prefix strategy, I added support for strategies in v1.50.1. Check it out.

Here are the docs:

[Documentation](https://s00d.github.io/nuxt-i18n-micro/guide/getting-started#%F0%9F%9A%A6-strategy-new-in-version-1-50-0)

**Comment by alexcroox** [comment]
Wow, thank you so much!! A couple of snags I've noticed in testing:

1. The `nitro.preset = 'cloudflare_pages'` restriction can now be removed if using `i18n.strategy = 'no_prefix'`?

2. Because of [const primaryLanguage = language.split('-')[0]](https://github.com/s00d/nuxt-i18n-micro/blob/98c7542331b1e51e23f3a52aa3ce8e459fc9b4e6/src/runtime/plugins/04.auto-detect.ts#L90) I can no longer use `en-GB` or `fr-FR` which might restrict the ability to provide regional differences in translations. Such as en-GB vs en-US.
3.  
![image](https://github.com/user-attachments/assets/c4e22770-d6d8-4165-8aa2-c3bf836a9c7b)
![image](https://github.com/user-attachments/assets/807ff75b-99c3-46c9-a76e-3681bf22697e)
![image](https://github.com/user-attachments/assets/0aa6de91-b910-42dd-a790-69054b86a513)

**Comment by alexcroox** [comment]
I've reverted back to using en-GB/fr-FR/de-DE with 1.50.4 and it's working as expected! Thanks!
