### ISSUE TITLE
Can we make Translation type compatible with string ?

### ISSUE THREAD

**Issue by valh1996** [s00d/nuxt-i18n-micro#81]
Hi,

_First of all, thank you for your package ✨ ! It's great to see other libs emerging for i18n that perform better._

I was wondering if it was possible to make the [`Translation`](https://github.com/s00d/nuxt-i18n-micro/blob/main/packages/core/src/types.ts#L8) type compatible with the `string` type?

Example with a [dropdown component](https://ui.nuxt.com/components/dropdown) which take a string label :
```ts
{
  label: t('See'),
  icon: 'i-lucide-eye',
  click: () => showSalarySlip(row.id)
}
```

The error is `Type [unkown] is not assignable to type [string].`

I am therefore obliged to add an assertion type: `t('See') as string`

**Comment by s00d** [comment]
need full ecaample

**Comment by valh1996** [comment]
```html
<script setup lang="ts">
const items = [
  [{
    label: t('See'), <!-- here : Type [unkown] is not assignable to type [string] -->
    icon: 'i-lucide-eye',
    click: () => showSalarySlip(row.id)
  }]
]
</script>

<template>
  <UDropdown :items="items" />
</template>
```

**Comment by alexcroox** [comment]
![SCR-20241211-ixwz](https://github.com/user-attachments/assets/5afbaeeb-5a91-49fb-8262-a1d2f2752634)

**Comment by s00d** [comment]
I need a complete example project, with settings and dependencies, so that I can understand something
