### ISSUE TITLE
<i18n-link> tag - External links handling does'nt work

### ISSUE THREAD

**Issue by TristanSurGithub** [s00d/nuxt-i18n-micro#83]
**Describe the bug**
When i use `<i18n-link>` tag for an external site, the redirection doesn't work.
`
<i18n-link to="www.external-link.fr">My external Link</i18n-link>
`
-> Result : `https://www.mydomain.fr/www.external-link.fr`, the external redirection doesn't work, it's an internal redirection.

**To Reproduce**
1. Use `
<i18n-link to="www.external-link.fr">My external Link</i18n-link>
` with external domain
2. Click on the link
3. The external redirection doesn't work, it's an internal redirection.

**Expected behavior**
Detect whether the `to` parameter is intended for an external website or an internal website. To redirect correctly if it's an internal or external link

**Additional context**
The documentation : [https://s00d.github.io/nuxt-i18n-micro/components/i18n-link#external-links-handling](https://s00d.github.io/nuxt-i18n-micro/components/i18n-link#external-links-handling)
I see that you're using `$localeRoute(to)` for the `to` parameter, so it doesn't matter whether it's an external link or an internal redirect, you redirect to internal link.

```typescript
<template>
  <NuxtLink
    :to="$localeRoute(to)"
    :style="activeStyle"
  >
    <slot>Go to Page</slot>
  </NuxtLink>
</template>
``` 

Thank you so much 🙂

**Comment by s00d** [comment]
I'm on vacation, I'll be back in a couple of days and I'll take a look

**Comment by s00d** [comment]
try v1.40.0
