### ISSUE TITLE
no_prefix still attempts to pre-render routes on build

### ISSUE THREAD

**Issue by alexcroox** [s00d/nuxt-i18n-micro#88]
v1.50.4 fails on build when using `strategy: "no_prefix"` due to pre-rendering pages that do not exist.

Maybe due to these hooks: ?

https://github.com/s00d/nuxt-i18n-micro/blob/main/src/module.ts#L317-L343

https://github.com/s00d/nuxt-i18n-micro/blob/main/src/module.ts#L382-L411

![SCR-20241223-hvrf](https://github.com/user-attachments/assets/f50ed93b-39fe-44f4-91b6-b15865e7958c)

My config:

```
i18n: {
    locales: [
      {
        code: 'en-GB',
        iso: 'en-GB',
      },
      {
        code: 'fr-FR',
        iso: 'fr-FR',
      },
      {
        code: 'de-DE',
        iso: 'de-DE',
      },
    ],
    defaultLocale: 'en-GB',
    fallbackLocale: 'en-GB',
    localeCookie: 'locale',
    disablePageLocales: true,
    autoDetectLanguage: true,
    strategy: 'no_prefix',
    autoDetectPath: '*',
  },
 ```

**Comment by s00d** [comment]
Try version v1.51.0; I'm not sure if that's where the issue was. If it doesn't help, create an example with the error.

**Comment by alexcroox** [comment]
v1.15.0 built without error, thanks!
