### ISSUE TITLE
can't invalidate cache on dev server

### ISSUE THREAD

**Issue by kleinpetr** [s00d/nuxt-i18n-micro#89]
With the latest versions I am facing an issue when locales seems to be cached during dev.
When I update any page specific locales, changes are not provided to the generated `_locales` data. When I visit `_locales/data` manually I see old version of this file.

How can I invalidate it?

**Comment by s00d** [comment]
hello. try v1.52.0

**Comment by kleinpetr** [comment]
solved. thx
