### ISSUE TITLE
Locale type infering from nuxt.config results in typecheck fail

### ISSUE THREAD

**Issue by danielklein-arch** [s00d/nuxt-i18n-micro#91]
**Describe the bug**
When I add some additional parameters to list of locales in nuxt.config Locale type does not have these which results in typecheck failing. For Example I have declared icon for each locale when I access that icon in app it works just fine but typecheck fails.

My current workaround is to use older version on package I'm currently using 1.31.9 where Locales does not have specific type and are of type any instead but when I upgrade to latest version I run into issue described above

**To Reproduce**
1. Go to `nuxt.config.ts`
2. in i18n-micro locales definition add some additional params
3. Use that additional param somewhere in the app
4. Run `pnpm typecheck`

**Screenshots**
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/f4f1a926-9228-4d8b-9697-2d9f1d924930" />

**Desktop (please complete the following information):**
 - OS: MacOS Sequioa
 - Browser Firefox
 - Version 15.1

**Comment by s00d** [comment]
Where did you see "name"? Somewhere in the docs? There's no such thing; there's only "displayName," both in the config and in the method.

```
locales: [
      { code: 'en', iso: 'en_EN', displayName: 'English' },
      { code: 'de', iso: 'de_DE', displayName: 'German' },
      { code: 'ru', iso: 'ru_RU', displayName: 'Russian' },
      { code: 'fr', iso: 'fr_FR', displayName: 'French' },
      { code: 'ch', iso: 'ch_CH', displayName: 'Chinese' },
    ],
```

**Comment by danielklein-arch** [comment]
I didn't take it from docs I just added my own params. That's how I've been doing with different packages before and they just Declared the type based on the `locales`

**Comment by s00d** [comment]
Here’s the interface:

```
export type LocaleCode = string

export interface Locale {
  code: LocaleCode
  disabled?: boolean
  iso?: string
  dir?: 'ltr' | 'rtl' | 'auto'
  displayName?: string
  baseUrl?: string
  baseDefault?: boolean
}
```

That’s why I asked, where did you see `name`? Maybe there’s an error somewhere. In version v1.54.0, I added `[key: string]: unknown` to allow passing and retrieving custom parameters.
