### ISSUE TITLE
 Migrating an Old Project to Use nuxt-i18n-micro: Request to Add an Option to Disable Automatic Language Package Loading (e.g., data.json)

### ISSUE THREAD

**Issue by lyingtech** [s00d/nuxt-i18n-micro#92]
**Is your feature request related to a problem? Please describe.**
I am trying to migrate an old project to a Nuxt.js application. In this project, I want to use nuxt-i18n-micro to manage multilingual routing while keeping vue-i18n as the main tool for language package management. However, I noticed that nuxt-i18n-micro automatically loads a data.json file for language data. This behavior conflicts with my existing setup, where I manually manage language packages (e.g., en.json and zh.json) using vue-i18n.
It is frustrating because I want to disable nuxt-i18n-micro's automatic language package loading and retain only its routing management functionality.

![image](https://github.com/user-attachments/assets/fda586fa-ac53-4a88-bc5d-479159f21dd5)

**Describe the solution you'd like**
I would like a configuration option in nuxt-i18n-micro to completely disable its automatic loading of language data (e.g., data.json). This would allow me to rely solely on vue-i18n for language package management while still utilizing nuxt-i18n-micro for routing purposes.

**Describe alternatives you've considered**
I attempted to manually override nuxt-i18n-micro's language loading by removing or replacing its default configuration, but it still loads data.json.
Another alternative is to stop using nuxt-i18n-micro altogether and manually configure routing, but this defeats the purpose of having a lightweight multilingual routing solution.

**Additional context**
export default {
  modules: ['nuxt-i18n-micro'],
  i18n: {
    locales: [
       { name: 'us',code: 'us', iso: 'en-US'},
       { name: 'uk',code: 'uk', iso: 'en-GB' }
    ],
    disablePageLocales: true,                                                                                                                                    08:54:24
    meta: false,
  },
};

In this setup, nuxt-i18n-micro automatically loads data.json, which I do not want. My expectation is to fully disable data.json loading and use the vue-i18n mechanism for handling language packages.

Thank you for your time and for considering this feature request!

**Comment by s00d** [comment]
In version v1.54.0, I added the ability to completely disable the plugin: [https://s00d.github.io/nuxt-i18n-micro/guide/getting-started#🧩-plugin](https://s00d.github.io/nuxt-i18n-micro/guide/getting-started#🧩-plugin). Give it a try, it should work.
